### ISSUE TITLE
Bug: Error message for editing telegram username not in line with what is allowed

### ISSUE THREAD

**Issue by cshao02** [AY2425S1-CS2103T-F09-2/tp#150]
![image](https://github.com/user-attachments/assets/cf2a38af-ddca-4a22-91c5-ec472ca9707c)

The error message that says telegram handle should not be blank only applies on adding of a person, but on editing a person, it can be blank to allow removal of the telegram handle to keep in line with the fact that the field is optional.

2 possible fixes:
- Make it such that it is not allowed to edit with t/ to remove a telegram handle
- Update the error message such that blank telegram input is allowed on edit

**Comment by brianchoon** [comment]
I believe the logical decision is to choose the second fix. Disallowing the removal of a telegram handle does not serve any practical purpose, in fact it reduces functionality of our app for the user.
