### ISSUE TITLE
Bug: Unable to assign multiple roles to a person when editing

### ISSUE THREAD

**Issue by brianchoon** [AY2425S1-CS2103T-F09-2/tp#167]
The `edit` command does not support the assigning of multiple roles to a person.

This effectively means that the only time we can assign multiple roles to a person is when adding the person for the first time in the address book.

Such commands should be valid:
```
edit 1 r/attendee r/sponsor
```

This will assign the roles `attendee` and `sponsor` to the person with index 1.

**Comment by chuajunyu** [comment]
Same as #116
