### ISSUE TITLE
[PE-D][Tester A] Unable to enter all number telegram username

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#238]
# Describe the bug

When entering an invalid Telegram username, PlanPal indicates that "Telegram Usernames should only contain alphanumeric characters and underscores, and be between 5 to 32 characters."

However, when trying to enter a username like "12345", which fits the criteria, PlanPal still fails to accept this username.

# Expected Behavior

Given the requirements for alphanumeric characters and at least 5 characters, all number usernames like "12345" should be allowed.

# Screenshots

![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/97032f87-d7ce-4b39-b26a-1425a1312a59.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AgentHagu/ped#2

**Comment by shardhrv** [comment]
Even though the screenshot is wrong, this issue is a real one and is easily reproduced.
