### ISSUE TITLE
[PE-D][Tester C] Add does not state the possible values for role

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-2/tp#240]
It is stated in edit but not add that there are only 4 fixed values that role can take for a given contact.

![image.png](https://raw.githubusercontent.com/KiKuasaurus/ped/main/files/c43f498a-d685-448f-b5f3-21452dfbb85d.png)

![image.png](https://raw.githubusercontent.com/KiKuasaurus/ped/main/files/21eb01db-4dc5-437c-a20c-e502c47c5d7d.png)

rationale for very low is that this is purely cosmetic and will not really affect usage. It is just inconvenient for a new user to not realise that roles are restricted until they key in a role that is not within the validated set of roles.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: KiKuasaurus/ped#5

**Comment by jan-kai1** [comment]
Group with #289

**Comment by shardhrv** [comment]
As this is duplicate with #289, I am closing this issue
