### ISSUE TITLE
[PE-D][Tester A] Non 8-digit length phone numbers allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-2/tp#242]
# Describe the Bug

Phone numbers are allowed to be lengths of 3 or more, seemingly without any limit.

# Expected Behaviour

The ability for phone numbers of very large lengths, like "99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999" is unusual and should be prevented.

Given the context of PlanPal being used for student planners in NUS, i.e. in Singapore, phone numbers could also be restricted to the same specifications as those in Singapore, such as phone numbers being 8 digits long.

# Screenshots

![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/3aaefe2a-afbd-44be-a472-d4b5ab4bfa05.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: AgentHagu/ped#3

**Comment by shardhrv** [comment]
Duplicate with #249. Closing issue
