### ISSUE TITLE
[PE-D][Tester A] find-name unexpected behaviour with special keywords

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#246]
# Describe the bug

When using `find-name`, if a normal keyword is specified first, followed by special keywords (such as numbers or special characters), the contacts listed seems to default to the first 2 contacts.

# Expected Behaviour

If a user uses such special keywords, the command either works as intended (trying to find a name with those special characters and usually failing since names aren't allowed to have special characters) or the special keywords are ignored.

# Screenshots

Normal result
![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/1ba393bc-e4c2-4b57-8981-63a6205453e4.png)

Unexpected results

![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/175acea7-132c-4055-bdf9-b645915c669f.png)

![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/0978112b-dbeb-4519-91db-391b4c58d7cf.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: AgentHagu/ped#5

**Comment by shardhrv** [comment]
This seems to echo the same problem as in #250, not closing for now but possible duplicate issue.
