### ISSUE TITLE
[PE-D][Tester C] Remove states contact not found

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-2/tp#254]
![image.png](https://raw.githubusercontent.com/KiKuasaurus/ped/main/files/048e04b8-4f5f-41c4-bcad-76dd57379925.png)
As can be seen here when remove is called after find is called it states that contact is not found.
Could be stated somewhere that the list cannot be filtered to another event when remove is called as it appears to work fine when all contacts are listed or the filter is set to the relevant event.
Rationale for low is that it is unlikely for someone to use the command in such a way but in the even that it is indeed used in such a way it could cause user confusion as to why it is not working correctly.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: KiKuasaurus/ped#6

**Comment by jan-kai1** [comment]
Don't think it is a bug? Could indicate on remove from event that the index refers to the currently displayed list

**Comment by jan-kai1** [comment]
This should be handled by #305?
