### ISSUE TITLE
[PE-D][Tester D] Event-Add: Editing json file directly causes display to be incorrect

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#263]
![image.png](https://raw.githubusercontent.com/antgyf/ped/main/files/01f20025-b645-4df1-a8fc-4b3e968383b1.png)

Total number of contacts linked to an event becomes incorrect after editing json file directly.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: antgyf/ped#3

**Comment by shardhrv** [comment]
Duplicate with #269
