### ISSUE TITLE
[PE-D][Tester E] User Story Issue

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#268]
![DG Bug (2).png](https://raw.githubusercontent.com/calebchongsj/ped/main/files/bac6a1e9-6f03-4e69-9eed-aa45bf87f102.png)

In this user story, the function and benefit for a student event planner should not be the same.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: calebchongsj/ped#9

**Comment by shardhrv** [comment]
I think that the textbook mentions that we do not need to have to fill out all three columns right? Please fact check me if I am wrong. As a fix, we can just delete the stuff that is under the "So that I can" portion

**Comment by shardhrv** [comment]
![image](https://github.com/user-attachments/assets/f6046947-a1a3-4faa-a89e-c6863c04f4fb)

Textbook, based on this I will omit the {benefit} duplicated
