### ISSUE TITLE
[PE-D][Tester D] Editing EventManager JSON File Directly: Added Contacts do not show up

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#269]
Adding a contact to an event eg. as an attendee causes the number to of attendees to increase, but subsequently calling find-event does not display the contacts properly.

![image.png](https://raw.githubusercontent.com/antgyf/ped/main/files/876affe0-0d4a-40d8-8f94-1345f0b56a46.png)

only 5 contacts when number of contacts in event is 7.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: antgyf/ped#4

**Comment by jan-kai1** [comment]
Not sure how to handle direct modification of JSON

**Comment by shardhrv** [comment]
Is there a way to update UI on save so counts of attendees can be updates also?

**Comment by jan-kai1** [comment]
Seems to be adding a contact which does not exist in the contact list to event, closing for now
