### ISSUE TITLE
[PE-D][Tester A] User Guide: Mismatch between format and example in check-excluded

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#277]
# Describe the bug
The user guide states that the format for the command is `check-excluded` but in the example, the command used is `checkexcluded` without the dash.

# Expected behaviour
Update the example to use the correct command format.

# Screenshots

![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/09079806-d247-4bf9-b0e9-7f554c65e3aa.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AgentHagu/ped#15

**Comment by shardhrv** [comment]
easy fix
