### ISSUE TITLE
[PE-D][Tester B] Remove contact from event error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-2/tp#278]
Gives invalid format error message for the following command, perhaps a warning that contact index should be a positive integer could be shown
![image.png](https://raw.githubusercontent.com/JumpyJay/ped/main/files/2184b742-a3b1-4510-8b81-0ca02a079d47.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: JumpyJay/ped#6

**Comment by jan-kai1** [comment]
could just change error message? or specify in UG all indices used as input should be non negative and within the displayed indices

**Comment by shardhrv** [comment]
Yeah, should be an easy fix overall

**Comment by brianchoon** [comment]
Closing this as we have fixed it.
