### ISSUE TITLE
[PE-D][Tester A] User Guide: Inaccurate format for exclude

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-2/tp#280]
# Describe the bug
The format given for `exclude` is exclude ci/INDEX, [MORE_INDICES]. This slightly inaccurate since it's missing the ellipsis "..." following the [MORE_INDICES] to indicate that we can provide more than 1 extra indices.

# Expected behaviour
The user guide should be updated to have a more accurate format.

# Screenshots
![image.png](https://raw.githubusercontent.com/AgentHagu/ped/main/files/91b475ac-444d-48e2-bcc2-f964de4912fc.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: AgentHagu/ped#16

**Comment by shardhrv** [comment]
easy fix also
