### ISSUE TITLE
[PE-D][Tester C] MSS shows use case of an undocumented feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-2/tp#286]
![image.png](https://raw.githubusercontent.com/KiKuasaurus/ped/main/files/415c583e-5a0b-4a39-98a6-4cc98d186d3e.png)
This feature is undocumented in the UG. Is there supposed to be a way to list based off fields?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: KiKuasaurus/ped#13

**Comment by jan-kai1** [comment]
Could alter use case
