### ISSUE TITLE
Implement `TelegramUsername` class for the telegram tag (`/t ...`) command

### ISSUE THREAD

**Issue by shardhrv** [AY2425S1-CS2103T-F09-2/tp#55]
Add the `TelegramUsername` class for the `/t ...` command logic. This issue is separate from implementing the parser for this command.

TODO: 
[ ] Implement `TelegramUsername` Class
~~[ ] Add Telegram Tag to Person~~ (Shift to #61)
~~[ ] Storage and loading of Telegram Tag~~ (Shift to #61)
[ ] Adding `TelegramUsername` to testcases

**Comment by chuajunyu** [comment]
I split some of the tasks here to #61
