### ISSUE TITLE
Implement parser for role tag

### ISSUE THREAD

**Issue by cshao02** [AY2425S1-CS2103T-F09-2/tp#59]
Implement a parser that will be able to call role command created in #54.

TODO
[ ] implement parser logic
[ ] call role command

**Comment by jan-kai1** [comment]
Can refer to ParserUtil.parseTags, issue with parseTags is it currently takes in a List<String> which only has 1 string, inside with the whole text after t/ e.g. t/ tag1 tag2 will result in a List<String> with 1 string "tag1 tag2". This gets rejected by the validation regex for tags as it does not allow spaces
